# Generated by Django 6.0.4 on 2026-04-24 21:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'survey_challenge',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'survey_enterprise',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('agro_forestry', 'Agro Forestry'), ('agro_ecology', 'Agro Ecology'), ('apiculture', 'Apiculture')], max_length=100, unique=True)),
            ],
            options={
                'db_table': 'survey_environmental_project',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'survey_resource',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='agent', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'survey_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_sub_clans', models.IntegerField(default=0)),
                ('number_of_bitubhi', models.IntegerField(default=0)),
                ('headquarters_address', models.TextField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('parish', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_frequency', models.CharField(blank=True, choices=[('once_year', 'Once a Year'), ('twice_year', 'Twice a Year'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('other', 'Other')], max_length=20, null=True)),
                ('meeting_other_text', models.TextField(blank=True, null=True)),
                ('total_households', models.IntegerField(default=0)),
                ('total_population', models.IntegerField(default=0)),
                ('male_population', models.IntegerField(default=0)),
                ('female_population', models.IntegerField(default=0)),
                ('youth_population', models.IntegerField(default=0)),
                ('clan_leader_photo', models.ImageField(blank=True, null=True, upload_to='clan_leaders/')),
                ('clan_leader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clan_leader_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('collector_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collector_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('collector_signature', models.TextField(blank=True, null=True)),
                ('clan_leader_title', models.CharField(blank=True, max_length=255, null=True)),
                ('clan_leader_signature', models.TextField(blank=True, null=True)),
                ('coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator_signature', models.TextField(blank=True, null=True)),
                ('chairperson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chairperson_signature', models.TextField(blank=True, null=True)),
                ('palm_oil_machines', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clans', to=settings.AUTH_USER_MODEL)),
                ('environmental_projects', models.ManyToManyField(blank=True, to='survey.environmentalproject')),
            ],
            options={
                'db_table': 'survey_clan',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('position', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('phone_contact', models.CharField(max_length=20)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_committee_member',
            },
        ),
        migrations.CreateModel(
            name='EducatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('education_level', models.CharField(choices=[('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=20)),
                ('area_of_specialization', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educated_persons', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_educated_person',
            },
        ),
        migrations.CreateModel(
            name='EducationEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=255)),
                ('population_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_of_employment', models.CharField(blank=True, max_length=255, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_estimates', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_education_estimate',
            },
        ),
        migrations.CreateModel(
            name='OBBLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('number_of_persons', models.IntegerField()),
                ('education_level', models.CharField(max_length=255)),
                ('positions_held', models.TextField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obb_leaders', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_obb_leader',
            },
        ),
        migrations.CreateModel(
            name='OfficeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.TextField()),
                ('structure_type', models.CharField(choices=[('permanent', 'Permanent'), ('semi_permanent', 'Semi-Permanent'), ('temporary', 'Temporary')], max_length=20)),
                ('number_of_staff', models.IntegerField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_office_structure',
            },
        ),
        migrations.CreateModel(
            name='PersonAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=255)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abroad_persons', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_person_abroad',
            },
        ),
        migrations.CreateModel(
            name='PoliticalLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('number_of_persons', models.IntegerField()),
                ('names', models.TextField()),
                ('contacts', models.TextField(blank=True, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_leaders', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_political_leader',
            },
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_unique_id', models.CharField(max_length=255, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_registered_device',
            },
        ),
        migrations.CreateModel(
            name='SavingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('reasons_if_no', models.TextField(blank=True, null=True)),
                ('formation_year', models.IntegerField(blank=True, null=True)),
                ('initiated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('registered', models.BooleanField(default=False)),
                ('membership_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shares_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_subscription', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adult_male', models.IntegerField(blank=True, null=True)),
                ('adult_female', models.IntegerField(blank=True, null=True)),
                ('youth_male', models.IntegerField(blank=True, null=True)),
                ('youth_female', models.IntegerField(blank=True, null=True)),
                ('coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator_education', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_officer_education', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_officer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('secretary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secretary_education', models.CharField(blank=True, max_length=255, null=True)),
                ('secretary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('treasurer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_education', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('heard_gov_programs', models.BooleanField(default=False)),
                ('benefited', models.BooleanField(default=False)),
                ('source_info', models.CharField(blank=True, max_length=255, null=True)),
                ('chairperson_terms', models.IntegerField(blank=True, null=True)),
                ('secretary_terms', models.IntegerField(blank=True, null=True)),
                ('treasurer_terms', models.IntegerField(blank=True, null=True)),
                ('last_election_year', models.IntegerField(blank=True, null=True)),
                ('clan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saving_group', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_saving_group',
            },
        ),
        migrations.CreateModel(
            name='SubClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('parish', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('subclan_leader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subclan_leader_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number_of_ridges', models.IntegerField(default=0)),
                ('education_primary', models.BooleanField(default=False)),
                ('education_secondary', models.BooleanField(default=False)),
                ('education_institution', models.BooleanField(default=False)),
                ('education_diploma', models.BooleanField(default=False)),
                ('education_university', models.BooleanField(default=False)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclans', to='survey.clan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subclans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_subclan',
            },
        ),
        migrations.CreateModel(
            name='Ridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('parish', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('ridge_leader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ridge_leader_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number_of_households', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ridges', to=settings.AUTH_USER_MODEL)),
                ('subclan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridges', to='survey.subclan')),
            ],
            options={
                'db_table': 'survey_ridge',
            },
        ),
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_data',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='clan',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clans', to='survey.surveydata'),
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('heritage_type', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('parish', models.CharField(max_length=255)),
                ('historical_usage', models.TextField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_water_source',
            },
        ),
        migrations.CreateModel(
            name='ClanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('clan', 'Clan'), ('subclan', 'Sub-Clan'), ('ridge', 'Ridge')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='survey.clan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_clan_assignment',
                'unique_together': {('clan', 'user', 'level')},
            },
        ),
        migrations.CreateModel(
            name='ClanChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.challenge')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='survey.clan')),
            ],
            options={
                'db_table': 'survey_clan_challenge',
                'unique_together': {('clan', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='ClanEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='survey.clan')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.enterprise')),
            ],
            options={
                'db_table': 'survey_clan_enterprise',
                'unique_together': {('clan', 'enterprise')},
            },
        ),
        migrations.CreateModel(
            name='ClanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_capacity', models.CharField(max_length=255)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('owned', models.BooleanField(default=False)),
                ('rented', models.BooleanField(default=False)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='survey.clan')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.resource')),
            ],
            options={
                'db_table': 'survey_clan_resource',
                'unique_together': {('clan', 'resource')},
            },
        ),
    ]
